[versions]
##########################################################################
# Plugins
# Check this on https://kotlinlang.org/docs/releases.html
kotlin = "2.3.0"
# Check this on https://plugins.gradle.org/plugin/org.jetbrains.intellij.platform/
intelliJPlatform = "2.10.5"
##########################################################################
# Java Configuration
# The Java version the JDK will be for compiling and running code.
# Check this on https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#platformVersions
java = "21"
# The Java version the JDK will be for running Gradle.
gradleJava = "25"
##########################################################################
# IntelliJ Metadata
platform = "2025.3"
gradle = "9.2.1"
##########################################################################
[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
